In [ ]:
# celda para acceder a archivos en Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Evaluación: NumPy y SciPy

## <font color='purple'>**Ejercicio 1**</font>



In [2]:
import numpy as np
numbers = np.arange(15)
print(numbers)

# Del arreglo "numbers" extraiga los últimos dos elementos

# Del arreglo "numbers" extraiga todos los números excepto los últimos dos elementos

# Obtenga de "numbers", a partir del segundo elemento, los elementos cada 2 posiciones (Por ejemplo: [0 1 2 3 4 5 6 7 8] -> [1 3 5 7])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print('últimos dos elementos:', numbers[-2:])
print('todos excepto los últimos dos:', numbers[:-2])
print('cada dos posiciones:', numbers[1::2])

últimos dos elementos: [13 14]
todos excepto los últimos dos: [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
cada dos posiciones: [ 1  3  5  7  9 11 13]


In [4]:
import numpy as np

In [5]:
#Crear un arreglo de NumPy a partir de una lista de números de Python

#Crear un arreglo 1D de NumPY con 10 números flotantes (con decimales dtype=float) inicializada con ceros

#Crear un arreglo 2D de NumPy con forma 3x3 con números flotantes

#Crear un arreglo con 12 números aleatorios


In [6]:
lista1=[1,2,3,4,5]
ar1=np.array(lista1)
print('arreglo 1:', ar1)

ar2=np.linspace(0,0.99,10)
print('arreglo 2:', ar2)

ar3=np.array([[1.,2,3],[4,5,6],[7,8,9]])
print('arreglo 3: \n', ar3,)

ar4=np.random.random(12)
print('arreglo 4:', ar4)

arreglo 1: [1 2 3 4 5]
arreglo 2: [0.   0.11 0.22 0.33 0.44 0.55 0.66 0.77 0.88 0.99]
arreglo 3: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
arreglo 4: [0.39414633 0.05193371 0.71382262 0.24870904 0.67798918 0.62375227
 0.95206496 0.09761107 0.68249324 0.76519134 0.61133267 0.51333969]


In [7]:
import numpy as np
arrayToMatrix = np.arange(36)
arrayToMatrix
# Convierta el arreglo arrayToMatrix a una matrix de forma 6x6

# Utilizando indexacion, extraiga la tercera fila de la matriz resultante (recuerde que se indexa a partir de 0)

# Utilizando slicing extraiga los elementos 14, 15, 20, 21 en una matrix 2x2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [8]:
matriz=arrayToMatrix.reshape([6,6])
print('Matriz generada a partir del arreglo: \n', matriz, '\n')

print('Segunda fila extraída: ' ,matriz[2,:], '\n')

slice=matriz.copy()[2:4,2:4]
print('Elementos específicos: \n', slice)

Matriz generada a partir del arreglo: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

Segunda fila extraída:  [12 13 14 15 16 17] 

Elementos específicos: 
 [[14 15]
 [20 21]]
