<div align="center">
    <h1>Taller de Computación Científica en Python - 2025</h1>
    <img src="https://www.iycr2014.org/__data/assets/image/0014/133052/logo_cenat.png" alt="Logo CENAT" style="width: 200px;"/>
    
</div>

---

## NumPy: Fundamento de Python científico  

<center> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1280px-NumPy_logo_2020.svg.png" alt="image info" width="300"/> </center>

En esta sección, se estudiará el uso de la librería NumPy como una herramienta para el manejo de arreglos de datos, matrices, y otros tipos de estructuras. Además, se revisarán las operaciones básicas involucradas y cómo obtener el mejor provecho de los recursos computacionales.

---

**Realizado por:**  
Johansell Villalobos y Julián Sánchez

In [6]:
# celda para acceder a archivos en Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


La utilización de arreglos, matrices y otros arreglos multi-dimensionales
son comunes en la computación numérica y científica.

- Idealmente, al operar sobre los elementos de un arreglo queremos evitar ciclos explícitos que complican legibilidad y lógica del código.
- Operaciones basadas en arreglos (vectorizadas)
- Código más conciso y ejecución más rápida



---



* En Python, NumPy es el "estándar" para trabajar con arreglos.
* Su núcleo está escrito en C, por lo que es más eficiente en el almacenamiento de datos.
* Tiene una implementación de arreglos muy poderosa, de carácter multidimensional.
* Engloba funciones de álgebra lineal, transformada de Fourier, etc.

# Arreglos (*arrays*) de NumPy

* Los arrays de NumPy son estructuras de datos **ordenadas**, de **cantidad fija de elementos** y un tipo de **dato uniforme**.
* Son los equivalentes a las matrices y los vectores en álgebra, por lo que se les puede aplicar operaciones.
* Por su implementación, son **más eficientes** que otras estructuras de datos nativas de Python. El código, además, es más conciso.

In [1]:
#Se debe importar la biblioteca NumPy
#Por covención se usa el alias np
import numpy as np

In [2]:
#Con el signo de ? podemos consultar la documentación de NumPy
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\pelot\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__init__.py'>
File:        c:\users\pelot\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for fur

## ¿Por qué se dice que es más conciso y eficiente?

In [3]:
array = np.arange(1e6) #Creamos un arreglo de 1 millón de elementos
                       #Queremos multiplicar por 5 cada elemento del arreglo

lista = list(array) #Lo convertimos en una lista | [1, 2, 3, 4] | y = [1*5]

#Medimos el tiempo de 10 loops ejecutados 5 veces

%timeit -n10 y = [val*5 for val in lista] #List comprehension, multiplicar por 5 cada valor

%timeit -n10 y = array*5 #NumPy ofrece operaciones aplicables directamente sobre el arreglo

160 ms ± 20.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.07 ms ± 272 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Creación de arreglos

Varias funciones sirven para crear arreglos de NumPy, entre ellas las siguientes:

| Función | Resultado |
| :---: | :---: |
| array() | Crea un arreglo con los datos especificados como estructuras de datos|
| empty() | Crea un arreglo vacío, con datos "basura"|
| zeros() | Crea un arreglo de ceros|
|ones() | Crea un arreglo de unos|
| full() | Crea un arreglo lleno del valor especificado|
| arange() | Crea un arreglo de valores indicando un valor inicial, un final y un step|
| linspace() | Crea un arreglo de valores indicando un valor inicial, un final y una cantidad deseada|
| logspace() |Crea un arreglo de valores con espaciado logarítmico|
| geomspace() |Crea un arreglo de valores con espaciado logarítmico en una progresión geométrica|
| random() | Crea una matriz de números entre 0.0 y 1.0|



In [4]:
arr = np.array([1,2,3]) #Array de dimensiones 1x3

print(arr,'\n')
print(np.array([[1],[2],[3]]),'\n') #Array de dimensiones 3x1
print(np.array([[1,2],[3,4]]),'\n') #Matrix 2x2

print(np.random.random([7,4]), '\n')
print("----------")

print(np.random.randn(3,3,3), '\n')


[1 2 3] 

[[1]
 [2]
 [3]] 

[[1 2]
 [3 4]] 

[[0.45666643 0.04934203 0.33076737 0.93760254]
 [0.15300884 0.62491393 0.36788993 0.7027512 ]
 [0.48722267 0.32187852 0.23330606 0.17802934]
 [0.69239688 0.35619765 0.93226598 0.02882919]
 [0.53398188 0.82328104 0.94855086 0.45224311]
 [0.43392803 0.96137701 0.57486506 0.72500409]
 [0.66092462 0.32934872 0.05513847 0.66761933]] 

----------
[[[ 0.66377614  0.13637273 -0.24685807]
  [ 0.77587853 -1.62382537  1.08571774]
  [-0.28917387  0.01638463 -0.59007997]]

 [[-1.34658919  0.0173235   0.33177612]
  [ 0.66142234 -0.37820817 -1.40281759]
  [-0.0520403   1.2129827   1.6232279 ]]

 [[ 0.51847478 -1.12158136  1.13886765]
  [-0.64647947 -0.27939965 -0.72750393]
  [-0.89452829  1.55184391 -0.75409247]]] 



In [5]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

* Observe que los arreglos se encierran entre **[]**, pero que al imprimir sus valores no están separados por comas como en las listas.
* Las dimensiones siempre se indican como **filas x columnas**.

### Crear arreglos con distintos valores iniciales

In [6]:
import numpy as np
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [7]:
arr1 = np.empty([3,4]) # Se indican [numero de filas, numero de columnas]
print(arr1,'\n')

arr1.fill(3)
print(arr1,'\n')

print(np.ones([5]),'\n') # Si se indica solo un número, supondrá que son columnas

print(np.full([2,2], np.inf)) # Crea una matriz rellena de "infinito"

[[1.34032894e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 3.76231868e+174 6.81017810e-091 4.00769607e+174]
 [1.00538988e-047 3.63978868e+175 3.99910963e+252 8.34402697e-309]] 

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]] 

[1. 1. 1. 1. 1.] 

[[inf inf]
 [inf inf]]


### Arreglos con secuencias incrementales

Un caso de uso muy común es crear un arreglo incremental desde 0 hasta algún valor arbitrario.

- Crearlo manualmente con np.array([0,1,2,...,N]) puede resultar inviable para arreglos muy grandes.



In [8]:
#La función de construcción arange provee esta funcionalidad.
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [9]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(50,100)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
#El tercer argumento de arange representa el incremento deseado o step
arr2 = np.arange(0,10,1.5) #Arreglo entre 0 y 10 (exceptuando al 10), con valores cada 1.5
print(arr2)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [13]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [14]:
#El tercer argumento de linspace representa la cantidad de datos deseados en el arreglo
arr3 = np.linspace(0,10,21) #Arreglo entre 0 y 10 (con 10), con 21 valores
print(arr3)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


La diferencia entre arange y linspace es que en el primero se define el intervalo o espaciado entre valores; mientras que con linspace se define la cantidad de valores


### Arreglos matriciales

Con las funciones anteriores se pueden crear matrices, pero existen también funciones para crear matrices con características específicas.

| Comando | Resultado |
| :---: | :---: |
| identity() | Crea una matriz identidad|
| eye() |Crea una matriz con unos en una diagonal (offset)|
| diag() |Crea una matriz con un arreglo arbitrario en la diagonal|


In [15]:
identidad = np.identity(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
np.eye?
offset = np.eye(4, k=1)
print(offset)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

El parámetro k hace la diagonal superior (k=1), inferior (k=-1) o principal.

In [17]:
diagonal = np.diag(np.arange(1,5,1))
print(diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### *List comprehension* y creación de arreglos

Se puede crear un arreglo a partir de listas directamente obtenidas de *list comprehension*.

In [18]:
a = [4.54,844,0.23]
print([i**2 for i in a])
print(np.array([i**2 for i in a]))

[20.6116, 712336, 0.0529]
[2.06116e+01 7.12336e+05 5.29000e-02]


## Comandos útiles para trabajar con arreglos de NumPy

Los arreglos de NumPy están acompañados de varias funciones y atributos que permiten manipularlos.

| Comando | Resultado |
| :---: | :---: |
| shape | Retorna una tupla con el número de elementos por dimensión|
| ndim | Dice el número de dimensiones|
| size | Dice cuántos elementos hay en un arreglo|
| dtype | Dice el tipo de datos que guarda un arreglo|
| T | Retorna la transpuesta de un arreglo|
|flatten() | Retorna el arreglo colapsado en una dimensión|
| fill() | Rellena el arreglo con el valor especificado|
| reshape() | Retorna un arreglo con el shape especificado|
| resize() | Cambia el tamaño y shape del arreglo|
| where() | Retorna los índices donde se cumplen las condiciones dadas|

In [19]:
arr = np.array([1,2,3]) #Array de dimension 1x3
arr

array([1, 2, 3])

In [20]:
arr = arr.reshape([3,1]) #Otra forma de crear un array 3x1
print(arr)

[[1]
 [2]
 [3]]


en reshape se especifica una tupla con la cantidad de [filas, columnas]

In [21]:
arr.T

array([[1, 2, 3]])

Algunas de estas funciones son muy útiles para entender las características de los objetos con los que estamos trabajando.

In [22]:
ident = np.identity(3) #Creando una matriz identidad de 3x3

print('Matriz: \n',ident,'\n')
print('Número de elementos: ',ident.size,'\n')
print('Forma (filas,columnas): ',ident.shape, '\n')
print('Cantidad de dimensiones: ', ident.ndim)

Matriz: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Número de elementos:  9 

Forma (filas,columnas):  (3, 3) 

Cantidad de dimensiones:  2


Otras nos permiten modificar la estructura del arreglo.

In [23]:
print(arr1)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [24]:
arr2 = np.resize(arr1,(7,2)) #Corta o agrega elementos según el tamaño especificado
print(arr2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
arr1 #resize() no modifica el arreglo original

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

Se pueden hacer operaciones sofisticadas como la búsqueda en arreglos según ciertas condiciones y la aplicación de operaciones sobre los elementos que cumplen la condición.

In [26]:
original = np.random.rand(3,3) #matriz 3x3 con números aleatorios entre 0 y 1
original

array([[0.99064913, 0.49181502, 0.94119724],
       [0.86076607, 0.27144198, 0.47449709],
       [0.52302016, 0.12036819, 0.57399903]])

In [27]:
np.where(original < 0.5) #Retorna los índices donde los valores son menores a 0.5, como array([filas]), array([columnas])

(array([0, 1, 1, 2], dtype=int64), array([1, 1, 2, 1], dtype=int64))

In [28]:
np.where?

Docstring:
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Example

In [29]:
#Para los números que cumplen la condición calculamos el cuadrado, para los otros el cubo

np.where(original < 0.5, original**2, original**3)

array([[0.97220888, 0.24188202, 0.83376169],
       [0.63775728, 0.07368075, 0.22514749],
       [0.14307221, 0.0144885 , 0.18911827]])

In [30]:
#Tal vez solamente necesitamos calcular el cuadrado de los que cumplen

np.where(original < 0, original**2, original)

array([[0.99064913, 0.49181502, 0.94119724],
       [0.86076607, 0.27144198, 0.47449709],
       [0.52302016, 0.12036819, 0.57399903]])

## <font color='purple'>**Ejercicio**</font>

Suponga que usted quiere graficar los valores de un modelo que depende de dos variables $X$ y $Y$ usando Python. Para ello, usted desea generar los valores de entrada de $X_0$ de $X_1$  **en dos columnas separadas de un solo arreglo**, considerando lo siguiente:

* El modelo es válido para $300 \leq X \leq 540$ y $300 \leq Y \leq 540$.
* Usted sabe que necesita 100 valores o más de ambas variables para obtener una buena resolución en la respuesta del modelo.

¿De qué forma podría crear este arreglo?


In [31]:
import numpy as np
ar=np.empty([100,2])
ar1=np.linspace(300,540,100) #se crea X y Y

ar.ndim
ar.size

#arreglo = np.array([ar1],[ar1])  no sirve, no se pueden combinar así
#ar.fill(ar1) no sirve porque solo se puede llenar así con un escalar

arreglo=np.column_stack((ar1,ar1)) #operación para combinar 2 arreglos 1-dim en 1 2-dim, uniéndolos como columnas
print(arreglo)

[[300.         300.        ]
 [302.42424242 302.42424242]
 [304.84848485 304.84848485]
 [307.27272727 307.27272727]
 [309.6969697  309.6969697 ]
 [312.12121212 312.12121212]
 [314.54545455 314.54545455]
 [316.96969697 316.96969697]
 [319.39393939 319.39393939]
 [321.81818182 321.81818182]
 [324.24242424 324.24242424]
 [326.66666667 326.66666667]
 [329.09090909 329.09090909]
 [331.51515152 331.51515152]
 [333.93939394 333.93939394]
 [336.36363636 336.36363636]
 [338.78787879 338.78787879]
 [341.21212121 341.21212121]
 [343.63636364 343.63636364]
 [346.06060606 346.06060606]
 [348.48484848 348.48484848]
 [350.90909091 350.90909091]
 [353.33333333 353.33333333]
 [355.75757576 355.75757576]
 [358.18181818 358.18181818]
 [360.60606061 360.60606061]
 [363.03030303 363.03030303]
 [365.45454545 365.45454545]
 [367.87878788 367.87878788]
 [370.3030303  370.3030303 ]
 [372.72727273 372.72727273]
 [375.15151515 375.15151515]
 [377.57575758 377.57575758]
 [380.         380.        ]
 [382.42424242

## Operaciones con arreglos de NumPy

* Se pueden hacer operaciones tanto con escalares como entre matrices y vectores.
* Estas operaciones se realizan según las reglas de álgebra lineal.

In [32]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr, '\n')

print(arr*2, '\n\n', arr/2, '\n\n', arr-10,'\n\n', arr+5, '\n') #Elemento por elemento

[[1 2]
 [3 4]] 

[[2 4]
 [6 8]] 

 [[0.5 1. ]
 [1.5 2. ]] 

 [[-9 -8]
 [-7 -6]] 

 [[6 7]
 [8 9]] 



In [33]:
print(np.full([2,2],2), '\n')
arr * np.full([2,2],2) # Multiplicación de arreglos

[[2 2]
 [2 2]] 



array([[2, 4],
       [6, 8]])

In [34]:
print(np.identity(2))
arr.dot(np.identity(2)) # Multiplicación de matrices
np.dot?

[[1. 0.]
 [0. 1.]]


Docstring:
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that 

## <font color='purple'> **Analicemos las funciones de NumPy vistas hasta ahora. ¿Cómo crearía un arreglo de elementos aleatorios tipo float entre 0 y 100?**</font>

In [35]:
a = np.random.rand(10)*100
print(a)

[31.1560081  79.00688682 97.31398743 46.74496361 77.62609301 68.77945641
 62.22457131 26.98163512 93.91829438 79.10129703]


### Operadores de reducción

En general, son operaciones que tienen como objetivo reducir las dimensiones del arreglo. *Ejemplo*: Producto punto.

| Comando | Resultado que retorna |
|:----------:|:------------:|
| argmax() | Índice donde ocurren los valores máximos |
| min()    | Valor mínimo |
| argmin() | Índice donde ocurren los valores mínimos |
| conj()   | Conjugado complejo de todos los elementos |\
| round()  | Valor redondeado de cada elemento |
| trace()  | Suma de las diagonales del arreglo |
| sum()    | Suma del arreglo |
| cumsum() | Suma acumulativa |
| mean()   | Media aritmética |
| var()    | Varianza|
| std()    | Desviación estándar |
| prod()   | Producto |
| cumprod()| Producto acumulativo |


In [36]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a.prod() #Producto de todos los elementos de un arreglo, en este caso sería 12!

479001600

In [38]:
b = np.array([[1+2j,2+2j],[1-2j,5-12j]]) #Matriz con números complejos
b

array([[1. +2.j, 2. +2.j],
       [1. -2.j, 5.-12.j]])

In [39]:
b.conj() #Conjugado del complejo

array([[1. -2.j, 2. -2.j],
       [1. +2.j, 5.+12.j]])

In [40]:
datos = np.array([402.23,384.60,384.21,409.58,374.42,402.06])

#Estadísticos descriptivos

print('Media: ', np.mean(datos))
print('Desviación estándar: ',np.std(datos))

Media:  392.84999999999997
Desviación estándar:  12.48384556136449


## Indexación y slicing

* Se puede acceder al índice o posición del elemento de un array con la sintaxis **[fila,columna]**.
* El slicing se consigue con **[inicio:final:step,inicio:final:step]** en el orden **[filas,columnas]**.

In [41]:
A = np.random.rand(6,6)
print(A)

[[0.33415237 0.10803672 0.97748072 0.21766711 0.14734943 0.88349474]
 [0.86802533 0.23722861 0.79639135 0.68277971 0.3978155  0.04966406]
 [0.79716856 0.84269802 0.79180095 0.67469531 0.55133977 0.00151649]
 [0.02530874 0.39855002 0.39956013 0.64669555 0.79620757 0.19306552]
 [0.69670782 0.33224828 0.08399762 0.25048955 0.38690204 0.68083299]
 [0.28872571 0.04079114 0.79805717 0.93406369 0.34301116 0.33852948]]


In [42]:
A[:, 2] #Extraer la tercera columna (índice 2)

array([0.97748072, 0.79639135, 0.79180095, 0.39956013, 0.08399762,
       0.79805717])

In [43]:
A[0:2,0:2]
A[:2, :2] #es lo mismo

array([[0.33415237, 0.10803672],
       [0.86802533, 0.23722861]])

In [44]:
A[4:6, 4:6]
A[-2:, -2:]

array([[0.38690204, 0.68083299],
       [0.34301116, 0.33852948]])

In [45]:
print(a,'\n')
print(a[1,1]) #se indica índice, devuelve valor en esa posición

a[:, 0:2] #todas las filas, primera y segunda columna

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

6


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

¡Cuidado! Al hacer *slicing*, no se copian los datos subyacentes.

In [46]:
original = np.array([1,2,3])
original

array([1, 2, 3])

In [47]:
trozo_Dif = original.copy()[:2]
trozo_Dif

array([1, 2])

In [48]:
trozo_Dif[0] = 9

In [49]:
original

array([1, 2, 3])

In [50]:
trozo = original[:2]
trozo

array([1, 2])

In [51]:
trozo[0] = 9 #modificar el primer elemento
trozo

array([9, 2])

In [52]:
original #¡Cambiamos el arreglo original!

array([9, 2, 3])

Los subarreglos que se extraen a través de *slicing* son vistas (views) de los datos originales. Hacen referencia a los mismos datos en memoria.



In [53]:
original = np.array([1,2,3])
trozo = original[:2]

modificado = np.copy(trozo) #básicamente una copia de la copia
modificado[0] = 9

print(original)
print(modificado)

[1 2 3]
[9 2]


## Broadcasting

*   Existen maneras de realizar cálculos con arreglos de diferente dimensionalidad en NumPy.
*   Se puede pensar en la analogía de una transmisión de datos a todos los elementos de un arreglo.

<center> <img src="https://numpy.org/doc/stable/_images/broadcasting_1.png" alt="image info" width="500"/> </center>


El tema broadcasting es un poco complejo pero útil, ya que puede reducir la cantidad de líneas de código en un cálculo. En el sitio oficial de [NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html) existe una explicación detallada de esta funcionalidad.

### Ejemplos:


In [54]:
a = np.array([1,2,3])
b = 2
print(a*b)

[2 4 6]


In [55]:
a = np.ones((3,5))
b = np.array([1,2,3])
print(a, '\n')
print(b, '\n')
print(a+b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[1 2 3] 



ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [56]:
# Para que el broadcasting funcione debe haber la misma cantidad de dimensiones
a = np.ones((3,5))
b = np.array([[1],[2],[3]]) # dims (3,1)
print(a, '\n')
print(b, '\n')
print(a+b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1]
 [2]
 [3]] 

[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


## Manejo de archivos con NumPy

* NumPy permite cargar datos de un archivo de texto con la función. Los datos se guardan en un array.
* **loadtxt()** es una de las funciones más usadas.



In [54]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [72]:
datos = np.loadtxt(open('/content/drive/MyDrive/TallerPythonCENAT/entrada.csv','r'),delimiter=',')

In [63]:
datos

array([[0.56445312, 0.7857666 , 0.66238403, 0.381073  , 0.76885986],
       [0.70596313, 0.89736938, 0.90246582, 0.88717651, 0.21951294],
       [0.00320435, 0.88973999, 0.27859497, 0.18301392, 0.10778809],
       [0.36602783, 0.15338135, 0.62615967,        nan, 0.98999023],
       [0.19818115, 0.00131226, 0.20666504, 0.55252075, 0.71081543],
       [0.90380859, 0.05490112, 0.70968628, 0.02615356, 0.91934204],
       [0.15689087, 0.85852051, 0.51434326, 0.75436401, 0.4425354 ],
       [0.56121826, 0.93249512, 0.30606079, 0.21484375, 0.42486572],
       [0.41104126, 0.82803345, 0.27801514,        nan, 0.85632324],
       [0.84790039, 0.80950928, 0.49990845, 0.05026245, 0.99301147]])

In [70]:
np.sqrt(datos)

array([[0.44517542, 0.03622507, 0.45460427, 0.7433174 , 0.84309871],
       [0.95068848, 0.23430989, 0.8424288 , 0.16172064, 0.95882326],
       [0.39609452, 0.92656382, 0.71717729, 0.86854131, 0.66523334],
       [0.74914502, 0.96565787, 0.55322761, 0.46351241, 0.65181725],
       [0.641125  , 0.90996343, 0.52727141,        nan, 0.92537735],
       [0.92081507, 0.89972733, 0.70704204, 0.22419289, 0.99649961]])

Con **skiprows** se puede omitir tantas filas como se desee.

In [67]:
datos = np.loadtxt(open('/content/drive/MyDrive/TallerPythonCENAT/entrada.csv','r'),delimiter=',',skiprows=4) #Ignora las primeras 4 filas
datos

array([[0.19818115, 0.00131226, 0.20666504, 0.55252075, 0.71081543],
       [0.90380859, 0.05490112, 0.70968628, 0.02615356, 0.91934204],
       [0.15689087, 0.85852051, 0.51434326, 0.75436401, 0.4425354 ],
       [0.56121826, 0.93249512, 0.30606079, 0.21484375, 0.42486572],
       [0.41104126, 0.82803345, 0.27801514,        nan, 0.85632324],
       [0.84790039, 0.80950928, 0.49990845, 0.05026245, 0.99301147]])

### Archivos con encabezados

Para cargar datos con encabezados en las columnas se utiliza **genfromtxt()**. Con esta función también se pueden leer archivos sin encabezado usando **names=False**.

In [81]:
#datos2 = np.loadtxt(open('/content/drive/MyDrive/TallerPythonCENAT/sismos.csv','r'),delimiter=',')
#datos2
#como hay encabezados, en vez de loadtxt se usa genfromtxt

datos2 = np.genfromtxt("/content/drive/MyDrive/TallerPythonCENAT/sismos.csv", dtype=float, delimiter=',', names=True)
np.genfromtxt?
datos2

array([(1990.,  5.,  6.,  1., 56., 3., 9.7489, -83.7534),
       (1991.,  4., 30.,  1., 55., 5., 9.7489, -83.7534),
       (1992.,  8., 31.,  2., 44., 3., 9.7489, -83.7534),
       (1993.,  7.,  3.,  3., 21., 4., 9.7489, -83.7534),
       (1993.,  9., 24.,  4., 39., 5., 9.7489, -83.7534),
       (1993., 11., 15.,  5., 17., 3., 9.7489, -83.7534),
       (1993.,  1., 16.,  8., 45., 7., 9.7489, -83.7534),
       (1997.,  2., 22.,  9., 44., 4., 9.7489, -83.7534),
       (1998.,  3., 12., 15., 54., 2., 9.7489, -83.7534),
       (1999., 11., 13., 15., 21., 3., 9.7489, -83.7534),
       (2000.,  2., 14., 16., 10., 8., 9.7489, -83.7534)],
      dtype=[('anio', '<f8'), ('mes', '<f8'), ('dia', '<f8'), ('hora', '<f8'), ('minuto', '<f8'), ('escala', '<f8'), ('latitud', '<f8'), ('longitud', '<f8')])

 * Se puede acceder a los nombres con el atributo **dtype.names**.
 * Para conocer los datos se puede usar el nombre de las columnas en vez del índice.

In [82]:
datos2.dtype.names


('anio', 'mes', 'dia', 'hora', 'minuto', 'escala', 'latitud', 'longitud')

In [85]:
datos2['escala']

array([3., 5., 3., 4., 5., 3., 7., 4., 2., 3., 8.])

### Guardar datos
**savetxt()** sirve para guardar datos.

In [87]:
arr = np.arange(0, 1000, 0.01)
arr

array([0.0000e+00, 1.0000e-02, 2.0000e-02, ..., 9.9997e+02, 9.9998e+02,
       9.9999e+02])

In [88]:
np.savetxt('salida.csv',arr, delimiter=',', fmt='%.2f') #fmt indica el formato de los decimales para cada float

*Pregunta: todo esto se aplica de la misma manera en un IDE o editor de código regular?*

In [89]:
np.linalg?